### ISSUE TITLE
Suggestion: Make the branch regex configurable

### ISSUE THREAD

**Issue by daggen** [thomasrepnik/idea-commit-prefix-plugin#27]
Thanks for a great plugin!
Can you make the regex for finding the ID from the branch to be configurable?
Also add possibility for prefix?

Example

I've the branch "sprint/123456-WithSomeText" and I would love to have my commit messages prefixed with:
#123456: 
# is the prefix and : is the sufix. 123456 is found from banch name by configurable regex

**Comment by OrtecJohnB** [comment]
Branch "sprint/123456-WithSomeText" does not work because the current version of the plugin only supports ticket systems like Jira that start the ticket ID with a project key followed by a dash. For example, ABC-1234 is a valid Jira ticket ID, but 1234 is not.

In my team we ran into this issue when we moved from Jira to Azure Boards. Therefore, we have made a change to the plugin to also support tickets that consist entirely of digits (like 1234). Branch "sprint/123456-WithSomeText" then works too. I am currently preparing a PR to hopefully get this merged and available to everybody.

**Comment by thomasrepnik** [comment]
Thank you both for your suggestions. I will not be able to look at it in
june. But i will give it a try in july/august.

Thank you for using my plugin and feel free to make a PR 🙂

OrtecJohnB ***@***.***> schrieb am Di., 11. Juni 2024, 09:54:

**Comment by OrtecJohnB** [comment]
> Thank you both for your suggestions. I will not be able to look at it in june. But i will give it a try in july/august. Thank you for using my plugin and feel free to make a PR 🙂 OrtecJohnB ***@***.***> schrieb am Di., 11. Juni 2024, 09:54:

PR https://github.com/thomasrepnik/idea-commit-prefix-plugin/pull/28 is open, looking forward to hearing from you!

> Thanks for a great plugin! Can you make the regex for finding the ID from the branch to be configurable? Also add possibility for prefix?
> 
> Example
> 
> I've the branch "sprint/123456-WithSomeText" and I would love to have my commit messages prefixed with: #123456:
> 
> # is the prefix and : is the sufix. 123456 is found from banch name by configurable regex

If you want to give my change a try, you can clone the repo, check out my branch, build the plugin locally and install it from disk. You will need to have the _Plugin DevKit_ plugin and follow these instructions: https://plugins.jetbrains.com/docs/intellij/publishing-plugin.html#building-distribution
Note that I have already incremented the version number to 1.4.0, so when using that version I am not sure you will get an update notification if Thomas publishes an update with that number or lower.

**Comment by thomasrepnik** [comment]
Thanks for the PR 🙌
Since I won't have my notebook with me for the next two weeks, I won't be able to try it out.
Will check it as soon as possible 👍
