### ISSUE TITLE
Commit message is highlighted

### ISSUE THREAD

**Issue by fj-dt** [thomasrepnik/idea-commit-prefix-plugin#8]
Hello,

First, thanks for your plugin, it's cool!

When I want to commit, my prefix is highlighted by default:

![image](https://user-images.githubusercontent.com/63464773/114297118-25db1080-9aaf-11eb-9582-05bc9e945efe.png)

I haven't found anything in the config to disable this. Is this something you could fix?
Also, by default it shows the last commit message, could it be possible to highlight this, but not the prefix?

Thanks!

**Comment by thomasrepnik** [comment]
it seems it's only possible to select/unselect the whole text. 
Currently there is no code in the plugin for selecting the text. This is done automatically by the IDE. 
Therefore i am closing the issue here. 

If someone has a hint on how to select only partial text in the commit dialog. Let me know 🙂
